
version: "3"
services:
  db:
    image: mdillon/postgis:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nauty_dev
      POSTGRES_HOST: db
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - nautynetwork

  backend:
    links:
      - db:db
    build:
      context: ./
      dockerfile: Dockerfile
#    command: gunicorn main:app --bind 0.0.0.0:3000
    env_file:
      - app/.env.dev
    volumes:
      - ./app:/app
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - nautynetwork
networks:
  nautynetwork:
    driver: bridge