"""Query log models

Revision ID: 65437f6ef142
Revises: fd064c09b747
Create Date: 2020-12-28 15:53:28.214973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65437f6ef142'
down_revision = 'fd064c09b747'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_string', sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_log')
    # ### end Alembic commands ###
